clickhouse_project:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 8123
      user: default
      password: mysecret
      schema: silver
      secure: False
      threads: 4
      connect_timeout: 10
