version: 2

models:
  - name: sunshine_monthly
    description: "Monthly aggregated sunshine data per station, derived from daily silver layer."
    columns:
      - name: staid
        description: "Station ID"
        tests: [not_null]
      - name: month
        description: "First day of month (month key)"
        tests: [not_null]
      - name: total_sunshine_hours
        description: "Total sunshine hours for the month"
      - name: avg_sunshine_hours
        description: "Average daily sunshine hours for the month"
